<a href="https://colab.research.google.com/github/moshehaimlevi/numpy.repo/blob/main/pandas6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
from IPython.display import display
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/sport_athletes.csv'

df = pd.read_csv(file_path)
display(df)

Mounted at /content/drive

,Country,Sport Type,Athlete Name,Height(cm),Weight(kg),Wins,Olympic Date
0,USA,Basketball,Michael Jordan,198,98,3,08/08/1992
1,USA,Basketball,LeBron James,206,113,2,15/08/2008
2,USA,Basketball,Kobe Bryant,198,96,2,24/08/2012
3,USA,Basketball,Kevin Durant,208,109,3,10/08/2016
4,USA,Basketball,Shaquille O'Neal,216,147,1,22/08/2000
5,Brazil,Soccer,Pelé,174,72,3,18/08/1970
6,Brazil,Soccer,Marta,163,57,3,01/08/2004
7,Portugal,Soccer,Cristiano Ronaldo,187,83,2,25/08/2008
8,Argentina,Soccer,Lionel Messi,170,69,2,11/08/2016
9,France,Soccer,Zinedine Zidane,185,80,3,17/08/1998
10,USA,Soccer,Megan Rapinoe,168,62,2,05/08/2020
11,USA,Swimming,Michael Phelps,193,88,5,16/08/2004
12,USA,Swimming,Katie Ledecky,180,58,4,25/08/2012
13,USA,Swimming,Caeleb Dressel,191,88,3,06/08/2016
14,Australia,Swimming,Ian Thorpe,196,85,4,11/08/2000
15,China,Swimming,Sun Yang,200,90,3,08/08/2012
16,Switzerland,Tennis,Roger Federer,185,85,2,28/07/2008
17,USA,Tennis,Serena Williams,175,70,4,01/08/2012
18,Spain,Tennis,Rafael Nadal,185,85,3,05/08/2016
19,Serbia,Tennis,Novak Djokovic,188,84,4,10/08/2020
20,Jamaica,Track and Field,Usain Bolt,195,94,6,22/08/2012
21,USA,Track and Field,Carl Lewis,188,81,4,15/08/1984
22,UK,Track and Field,Mo Farah,176,65,5,05/08/2016
23,USA,Track and Field,Florence Griffith,165,57,4,18/08/1988
24,USA,Track and Field,Ashton Eaton,185,77,3,08/08/2016
25,UK,Cycling,Chris Froome,180,70,4,08/08/2012
26,Belgium,Cycling,Eddy Merckx,181,72,5,15/08/1980
27,Slovenia,Cycling,Tadej Pogacar,184,69,3,11/08/2020
28,Slovenia,Cycling,Primoz Roglic,186,68,3,05/08/2016
29,UK,Cycling,Geraint Thomas,183,71,4,08/08/2008
30,Netherlands,Cycling,Anna van der Breggen,175,68,4,10/08/2020
31,USA,Gymnastics,Simone Biles,142,48,5,05/08/2016
32,Romania,Gymnastics,Nadia Comaneci,155,50,5,18/08/1976
33,USA,Gymnastics,Aly Raisman,160,52,3,10/08/2012
34,USA,Gymnastics,Shawn Johnson,157,50,3,15/08/2008
35,USA,Gymnastics,Gabby Douglas,150,45,3,11/08/2016

In [25]:
######################## QUESTION 1 ########################
df['Max weight'] = df['Weight(kg)'].max()
display()
df['Max height'] = df['Height(cm)'].max()
display()
df['Max wins'] = df['Wins'].max()
display(df)
#### OPTION 2 ####
######################## QUESTION 1 ########################
df_max = df.groupby(['Height(cm)', 'Weight(kg)', 'Wins']).max()
display(df_max)

,Country,Sport Type,Athlete Name,Height(cm),Weight(kg),Wins,Olympic Date,Max weight,Max height,Max wins
0,USA,Basketball,Michael Jordan,198,98,3,08/08/1992,147,216,6
1,USA,Basketball,LeBron James,206,113,2,15/08/2008,147,216,6
2,USA,Basketball,Kobe Bryant,198,96,2,24/08/2012,147,216,6
3,USA,Basketball,Kevin Durant,208,109,3,10/08/2016,147,216,6
4,USA,Basketball,Shaquille O'Neal,216,147,1,22/08/2000,147,216,6
5,Brazil,Soccer,Pelé,174,72,3,18/08/1970,147,216,6
6,Brazil,Soccer,Marta,163,57,3,01/08/2004,147,216,6
7,Portugal,Soccer,Cristiano Ronaldo,187,83,2,25/08/2008,147,216,6
8,Argentina,Soccer,Lionel Messi,170,69,2,11/08/2016,147,216,6
9,France,Soccer,Zinedine Zidane,185,80,3,17/08/1998,147,216,6
10,USA,Soccer,Megan Rapinoe,168,62,2,05/08/2020,147,216,6
11,USA,Swimming,Michael Phelps,193,88,5,16/08/2004,147,216,6
12,USA,Swimming,Katie Ledecky,180,58,4,25/08/2012,147,216,6
13,USA,Swimming,Caeleb Dressel,191,88,3,06/08/2016,147,216,6
14,Australia,Swimming,Ian Thorpe,196,85,4,11/08/2000,147,216,6
15,China,Swimming,Sun Yang,200,90,3,08/08/2012,147,216,6
16,Switzerland,Tennis,Roger Federer,185,85,2,28/07/2008,147,216,6
17,USA,Tennis,Serena Williams,175,70,4,01/08/2012,147,216,6
18,Spain,Tennis,Rafael Nadal,185,85,3,05/08/2016,147,216,6
19,Serbia,Tennis,Novak Djokovic,188,84,4,10/08/2020,147,216,6
20,Jamaica,Track and Field,Usain Bolt,195,94,6,22/08/2012,147,216,6
21,USA,Track and Field,Carl Lewis,188,81,4,15/08/1984,147,216,6
22,UK,Track and Field,Mo Farah,176,65,5,05/08/2016,147,216,6
23,USA,Track and Field,Florence Griffith,165,57,4,18/08/1988,147,216,6
24,USA,Track and Field,Ashton Eaton,185,77,3,08/08/2016,147,216,6
25,UK,Cycling,Chris Froome,180,70,4,08/08/2012,147,216,6
26,Belgium,Cycling,Eddy Merckx,181,72,5,15/08/1980,147,216,6
27,Slovenia,Cycling,Tadej Pogacar,184,69,3,11/08/2020,147,216,6
28,Slovenia,Cycling,Primoz Roglic,186,68,3,05/08/2016,147,216,6
29,UK,Cycling,Geraint Thomas,183,71,4,08/08/2008,147,216,6
30,Netherlands,Cycling,Anna van der Breggen,175,68,4,10/08/2020,147,216,6
31,USA,Gymnastics,Simone Biles,142,48,5,05/08/2016,147,216,6
32,Romania,Gymnastics,Nadia Comaneci,155,50,5,18/08/1976,147,216,6
33,USA,Gymnastics,Aly Raisman,160,52,3,10/08/2012,147,216,6
34,USA,Gymnastics,Shawn Johnson,157,50,3,15/08/2008,147,216,6
35,USA,Gymnastics,Gabby Douglas,150,45,3,11/08/2016,147,216,6

In [33]:
######################## QUESTION 2 ########################
df_highest = df.nlargest(2, 'Height(cm)')
display(df_highest)

,Country,Sport Type,Athlete Name,Height(cm),Weight(kg),Wins,Olympic Date,Max weight,Max height,Max wins
4,USA,Basketball,Shaquille O'Neal,216,147,1,22/08/2000,147,216,6
3,USA,Basketball,Kevin Durant,208,109,3,10/08/2016,147,216,6

In [35]:
######################## QUESTION 4 ########################
new_rows = pd.DataFrame({
    'Country': ['Canada', 'USA'],
    'Sport Type': ['Hockey', 'Skiing'],
    'Athlete Name': ['Wayne Gretzky', 'Lindsey Vonn'],
    'Height (cm)': [183, 172],
    'Weight (kg)': [84, 68],
    'Victory': [3, 4],
    'Olympic Date': ['01/02/2002', '12/02/2010']
})

df_new = pd.concat([df, new_rows])
display(df_new)

,Country,Sport Type,Athlete Name,Height(cm),Weight(kg),Wins,Olympic Date,Max weight,Max height,Max wins,Height (cm),Weight (kg),Victory
0,USA,Basketball,Michael Jordan,198.0,98.0,3.0,08/08/1992,147.0,216.0,6.0,NaN,NaN,NaN
1,USA,Basketball,LeBron James,206.0,113.0,2.0,15/08/2008,147.0,216.0,6.0,NaN,NaN,NaN
2,USA,Basketball,Kobe Bryant,198.0,96.0,2.0,24/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
3,USA,Basketball,Kevin Durant,208.0,109.0,3.0,10/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
4,USA,Basketball,Shaquille O'Neal,216.0,147.0,1.0,22/08/2000,147.0,216.0,6.0,NaN,NaN,NaN
5,Brazil,Soccer,Pelé,174.0,72.0,3.0,18/08/1970,147.0,216.0,6.0,NaN,NaN,NaN
6,Brazil,Soccer,Marta,163.0,57.0,3.0,01/08/2004,147.0,216.0,6.0,NaN,NaN,NaN
7,Portugal,Soccer,Cristiano Ronaldo,187.0,83.0,2.0,25/08/2008,147.0,216.0,6.0,NaN,NaN,NaN
8,Argentina,Soccer,Lionel Messi,170.0,69.0,2.0,11/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
9,France,Soccer,Zinedine Zidane,185.0,80.0,3.0,17/08/1998,147.0,216.0,6.0,NaN,NaN,NaN
10,USA,Soccer,Megan Rapinoe,168.0,62.0,2.0,05/08/2020,147.0,216.0,6.0,NaN,NaN,NaN
11,USA,Swimming,Michael Phelps,193.0,88.0,5.0,16/08/2004,147.0,216.0,6.0,NaN,NaN,NaN
12,USA,Swimming,Katie Ledecky,180.0,58.0,4.0,25/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
13,USA,Swimming,Caeleb Dressel,191.0,88.0,3.0,06/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
14,Australia,Swimming,Ian Thorpe,196.0,85.0,4.0,11/08/2000,147.0,216.0,6.0,NaN,NaN,NaN
15,China,Swimming,Sun Yang,200.0,90.0,3.0,08/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
16,Switzerland,Tennis,Roger Federer,185.0,85.0,2.0,28/07/2008,147.0,216.0,6.0,NaN,NaN,NaN
17,USA,Tennis,Serena Williams,175.0,70.0,4.0,01/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
18,Spain,Tennis,Rafael Nadal,185.0,85.0,3.0,05/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
19,Serbia,Tennis,Novak Djokovic,188.0,84.0,4.0,10/08/2020,147.0,216.0,6.0,NaN,NaN,NaN
20,Jamaica,Track and Field,Usain Bolt,195.0,94.0,6.0,22/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
21,USA,Track and Field,Carl Lewis,188.0,81.0,4.0,15/08/1984,147.0,216.0,6.0,NaN,NaN,NaN
22,UK,Track and Field,Mo Farah,176.0,65.0,5.0,05/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
23,USA,Track and Field,Florence Griffith,165.0,57.0,4.0,18/08/1988,147.0,216.0,6.0,NaN,NaN,NaN
24,USA,Track and Field,Ashton Eaton,185.0,77.0,3.0,08/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
25,UK,Cycling,Chris Froome,180.0,70.0,4.0,08/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
26,Belgium,Cycling,Eddy Merckx,181.0,72.0,5.0,15/08/1980,147.0,216.0,6.0,NaN,NaN,NaN
27,Slovenia,Cycling,Tadej Pogacar,184.0,69.0,3.0,11/08/2020,147.0,216.0,6.0,NaN,NaN,NaN
28,Slovenia,Cycling,Primoz Roglic,186.0,68.0,3.0,05/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
29,UK,Cycling,Geraint Thomas,183.0,71.0,4.0,08/08/2008,147.0,216.0,6.0,NaN,NaN,NaN
30,Netherlands,Cycling,Anna van der Breggen,175.0,68.0,4.0,10/08/2020,147.0,216.0,6.0,NaN,NaN,NaN
31,USA,Gymnastics,Simone Biles,142.0,48.0,5.0,05/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
32,Romania,Gymnastics,Nadia Comaneci,155.0,50.0,5.0,18/08/1976,147.0,216.0,6.0,NaN,NaN,NaN
33,USA,Gymnastics,Aly Raisman,160.0,52.0,3.0,10/08/2012,147.0,216.0,6.0,NaN,NaN,NaN
34,USA,Gymnastics,Shawn Johnson,157.0,50.0,3.0,15/08/2008,147.0,216.0,6.0,NaN,NaN,NaN
35,USA,Gymnastics,Gabby Douglas,150.0,45.0,3.0,11/08/2016,147.0,216.0,6.0,NaN,NaN,NaN
0,Canada,Hockey,Wayne Gretzky,NaN,NaN,NaN,01/02/2002,NaN,NaN,NaN,183.0,84.0,3.0
1,USA,Skiing,Lindsey Vonn,NaN,NaN,NaN,12/02/2010,NaN,NaN,NaN,172.0,68.0,4.0